import { copyFileSync, mkdirSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";
const outdir = production ? "build" : "sandbox/.obsidian/plugins/plugin";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	format: "cjs",
	platform: "browser",
	target: "es2018",
	outfile: `${outdir}/main.js`,
	minify: production,
	sourcemap: production ? false : "inline",
	treeShaking: true,
	logLevel: "info",
	define: {
		"process.env.NODE_ENV": JSON.stringify(production ? "production" : "development"),
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		"@lezer/*",
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
});

if (production) {
	await context.rebuild();
	// The release workflow uploads everything in the output directory.
	mkdirSync(outdir, { recursive: true });
	copyFileSync("manifest.json", `${outdir}/manifest.json`);
	await context.dispose();
} else {
	await context.watch();
}
