name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: "latest"

      - name: Build plugin
        run: |
          bun install
          bun run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          cd ./build

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            --verify-tag \
            main.js manifest.json styles.css